# Generated by Django 5.1.15 on 2026-09-21 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(db_index=True)),
                ('end_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('no_show', 'No Show')], db_index=True, default='confirmed', max_length=20)),
                ('service_name', models.CharField(max_length=150)),
                ('service_duration', models.PositiveIntegerField(help_text='Duration in minutes captured at booking time')),
                ('service_price', models.DecimalField(decimal_places=2, help_text='Price captured at booking time', max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('cancelled_by', models.CharField(blank=True, choices=[('customer', 'Customer'), ('provider', 'Provider'), ('admin', 'Admin')], max_length=20, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.TextField(blank=True)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_bookings', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provider_bookings', to='providers.providerprofile')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='providers.service')),
            ],
            options={
                'ordering': ['start_at'],
                'indexes': [models.Index(fields=['provider', 'start_at'], name='bookings_bo_provide_3bbc05_idx'), models.Index(fields=['customer', 'start_at'], name='bookings_bo_custome_68f0f9_idx'), models.Index(fields=['status', 'start_at'], name='bookings_bo_status_1b0540_idx'), models.Index(fields=['created_at'], name='bookings_bo_created_1720a2_idx')],
            },
        ),
    ]
