# Generated by Django 5.1.15 on 2026-09-21 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(db_index=True, max_length=200)),
                ('category', models.CharField(choices=[('clinic', 'Clinic / Healthcare'), ('salon', 'Salon & Spa'), ('tutor', 'Tutoring & Education'), ('fitness', 'Fitness & Personal Training'), ('consulting', 'Consulting & Legal'), ('other', 'Other Services')], db_index=True, default='other', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('slot_interval_minutes', models.IntegerField(choices=[(10, '10 minutes'), (15, '15 minutes'), (20, '20 minutes'), (30, '30 minutes'), (60, '60 minutes')], default=30, help_text='Granularity of generated time slots')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='If deactivated, provider is hidden from directory and cannot receive new bookings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['business_name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('duration_minutes', models.PositiveIntegerField(help_text='Service duration in minutes (must be multiple of 5 between 5 and 480)')),
                ('price', models.DecimalField(decimal_places=2, help_text='Cost of the service', max_digits=10)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Deactivated services are hidden from new booking requests')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='providers.providerprofile')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TimeOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(db_index=True)),
                ('end_at', models.DateTimeField(db_index=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_offs', to='providers.providerprofile')),
            ],
            options={
                'verbose_name_plural': 'Time Offs',
                'ordering': ['start_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='providers.providerprofile')),
            ],
            options={
                'verbose_name_plural': 'Working Hours',
                'ordering': ['weekday', 'start_time'],
            },
        ),
    ]
